development:
  adapter: postgresql
  database: hink_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: hink_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: hink
  pool: 5
  timeout: 5000
